# Generated by Django 3.2.6 on 2022-01-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20211231_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='header_img',
            field=models.ImageField(blank=True, null=True, upload_to='header/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(blank=True, default='default_user_profile.jpeg', null=True, upload_to='profile/'),
        ),
    ]
