# Generated by Django 3.2.6 on 2022-01-07 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20220106_1334'),
        ('user', '0010_follow_created_at'),
    ]

    operations = [
    ]
