# Generated by Django 3.2.6 on 2022-01-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_merge_0009_auto_20220106_1334_0010_follow_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(blank=True, default='profile/default_user_profile.jpeg', null=True, upload_to='profile/'),
        ),
    ]
