# Generated by Django 3.2.6 on 2022-01-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20220107_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemedia',
            name='media',
            field=models.ImageField(upload_to='profile/'),
        ),
    ]
