# Generated by Django 3.2.6 on 2022-01-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_socialaccount_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='account_id',
            field=models.CharField(max_length=30),
        ),
    ]
