# Generated by Django 3.2.6 on 2022-01-28 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20220122_1824'),
        ('user', '0016_alter_socialaccount_account_id'),
    ]

    operations = [
    ]
