# Generated by Django 3.2.6 on 2022-01-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_user_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=14, null=True, unique=True)),
                ('email', models.EmailField(max_length=100, null=True, unique=True)),
                ('auth_code', models.PositiveIntegerField()),
            ],
        ),
    ]
