# Generated by Django 3.2.6 on 2021-12-25 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_type', models.PositiveSmallIntegerField(choices=[(1, 'regular'), (2, 'reply'), (3, 'retweet'), (4, 'quote_retweet')])),
                ('retweeting_user', models.CharField(blank=True, max_length=20)),
                ('reply_to', models.CharField(blank=True, max_length=20)),
                ('content', models.CharField(max_length=500)),
                ('media', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to='tweet.tweet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Retweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retweeted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retweeted_by', to='tweet.tweet')),
                ('retweeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retweeting', to='tweet.tweet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retweets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replied', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replied_by', to='tweet.tweet')),
                ('replying', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replying_to', to='tweet.tweet')),
            ],
        ),
    ]
