# Generated by Django 3.2.6 on 2021-12-31 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0004_alter_reply_replied'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='retweet',
            constraint=models.UniqueConstraint(fields=('user', 'retweeted'), name='unique retweet'),
        ),
        migrations.AddConstraint(
            model_name='userlike',
            constraint=models.UniqueConstraint(fields=('user', 'liked'), name='unique like'),
        ),
    ]
