# Generated by Django 3.2.6 on 2022-01-06 11:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0007_alter_tweet_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='written_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
