# Generated by Django 3.2.6 on 2022-01-06 13:34

from django.db import migrations, models
import django.db.models.deletion
import tweet.models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0008_auto_20220106_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='media',
        ),
        migrations.CreateModel(
            name='TweetMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to=tweet.models.media_directory_path)),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='tweet.tweet')),
            ],
        ),
    ]
