# Generated by Django 3.2.6 on 2022-01-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0009_auto_20220106_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='user',
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweet_type',
            field=models.CharField(choices=[('GENERAL', 'general'), ('REPLY', 'reply'), ('RETWEET', 'retweet')], max_length=10),
        ),
    ]
