# Generated by Django 3.2.6 on 2022-01-06 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0010_auto_20220106_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quoted',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quoted_by', to='tweet.tweet'),
            preserve_default=False,
        ),
    ]
