# Generated by Django 3.2.6 on 2022-01-18 19:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0011_alter_quote_quoted'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlike',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
