# Generated by Django 3.2.6 on 2022-01-26 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0012_userlike_created_at'),
        ('notification', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify_in', to='tweet.tweet'),
        ),
    ]
