# Generated by Django 3.2.6 on 2022-01-28 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0012_userlike_created_at'),
        ('notification', '0003_alter_notification_tweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='noti_type',
            field=models.CharField(choices=[('LIKE', 'like'), ('REPLY', 'reply'), ('RETWEET', 'retweet'), ('FOLLOW', 'follow'), ('MENTION', 'mention')], max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='tweet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notify_in', to='tweet.tweet'),
        ),
    ]
